electron-app/src/server/websites/artconomy/artconomy.service.ts

This pull request adds journal URL logging to the Artconomy module. Previously the post would succeed but not give the user a URL to check for output.
1. Create a new journal post on Artconomy
2. Check the log output and find the URL is present.
**Reviewers**

Add URL output for Artconomy journals.

---

electron-app/src/server/websites/artconomy/artconomy.service.ts

This pull request corrects the expansion of Artconomy profile URLs via the `ac` markup tag.
1. Create a new file post.
2. In the description of the file post, add in an ac user tag, like `{ac:Fox}`
3. Post the file
4. Visit the post in your browser and verify the link visits the profile.
**Reviewers**

Fix ac markup tag expansion.

---

electron-app/src/server/websites/artconomy/artconomy.service.ts

This PR updates the endpoints to match the revised schema for Artconomy's API. We're dropping the version markers since we're not actually using versioning so it creates a broken expectation that the API is not ever evolving. Some future versioning schema may be imposed, but as active practice is constant evolution, no version promises should be made.
1. Step by step manual setup/testing/verification instructions for your reviewers go here. Make sure you (the author) have already manually tested it using the same steps.
2. Step 2
**Author notes and concerns**:
1. I was having a hard time getting the develop branch to run. I may have just forgotten how-- so I haven't managed to test this myself.
2. The changes on Artconomy's end are already live. I've got a shim …

fix: Update Artconomy endpoints to match current schema.

---

ui/src/websites/artconomy/Artconomy.tsx
ui/src/websites/artconomy/providers.tsx
ui/src/websites/e621/e621.tsx
ui/src/websites/e621/providers.tsx

This PR adds autocomplete for Artconomy's tags, and requires a minimum of 5 tags to match the backend, which was recently updated to require minimum tagging requirements.
1. Create a new file and ready it for submission on Artconomy
2. Start to type a tag name
3. Observe autocompletion
4. Observe notice of minimum 5 tags

fix: Artconomy minimum tag count.

---

README.md
ui/package.json

This PR adds in some basic instructions for starting on development. These are the commands I currently use to work on the project.
**Author notes and concerns**:
I'm not sure this is the best workflow available, but it works for me. I've tried using `npm run start:dev` in the `electron-app` directory but it does not seem to work.

docs: Add basic development setup instructions.

---

commons/src/interfaces/settings/settings.interface.ts
electron-app/src/app/settings.ts
electron-app/src/main.ts
ui/src/stores/settings.store.ts
ui/src/views/settings/SettingsView.tsx
ui/src/views/submissions/submission-forms/form-sections/DefaultFormSection.tsx
ui/src/views/submissions/submission-forms/interfaces/submission-section.interface.ts

This PR adds a new setting to select a default tag search provider, allowing the main tag field to query available supported providers for their tag listings.
**Dependencies**: https://github.com/mvdicarlo/postybirb-plus/pull/161
**Screenshots**: 
1. Create a new file submission
2. Observe no autocompletion with the default setting selected.
3. Enter settings. Under Posting, select the Artconomy provider.
4. Observe autocompletion from Artconomy in the main tag field.
5. Enter settings. Under Posting, select the e621 provider.
6. Observe autocompletion from e621 in the main tag field.
**Author notes and concerns**:
The default is no provider. It might be better to set a default-- likely e621 because their tag library is better, more consistent, and more …

feat: Default tag search provider

---

commons/src/interfaces/websites/itaku/itaku.file.options.interface.ts
commons/src/interfaces/websites/itaku/itaku.notification.options.interface.ts
commons/src/websites/itaku/itaku.file.options.ts
commons/src/websites/itaku/itaku.notification.options.ts
electron-app/src/server/websites/itaku/itaku.service.ts
ui/src/websites/itaku/Itaku.tsx

Analogous to other spoiler text implementations. Ancillary work during implementation of #170.
Edit: also removes the NSFL/Extreme rating category, because that got removed when content warnings were added to the site. Thanks ArgonVile for pointing that out.

Allow adding content warnings to Itaku posts

---

electron-app/src/server/websites/inkbunny/inkbunny.service.ts
ui/src/websites/inkbunny/Inkbunny.tsx

Since you might have a submission that is both sexual and violent or something. To fit with the one-dimensional idea of ratings, this now offers all combinations as separate buttons. It could be done as checkboxes instead too, but this way works fine without reinventing the whole ratings concept in multiple dimensions.
Names got shortened a bit to avoid buttons spilling to the next line quite as easily.
More ancillary work during implementation of #170.

Allow all combinations of Inkbunny ratings

---

commons/src/index.ts
commons/src/interfaces/submission/submission-create.interface.ts
commons/src/interfaces/submission/submission-import.interface.ts
electron-app/src/app/preload.ts
electron-app/src/server/submission/models/submission-create.model.ts
electron-app/src/server/submission/models/submission-import.model.ts
electron-app/src/server/submission/submission-importer/importers/activity-pub-importer.ts
electron-app/src/server/submission/submission-importer/importers/fa-archive-importer.ts
electron-app/src/server/submission/submission-importer/importers/file-list-importer.ts
electron-app/src/server/submission/submission-importer/importers/importer.ts
electron-app/src/server/submission/submission-importer/submission-importer.module.ts
electron-app/src/server/submission/submission-importer/submission-importer.service.ts
electron-app/src/server/submission/submission.controller.ts
electron-app/src/server/submission/submission.module.ts
electron-app/src/server/submission/submission.service.ts
ui/src/index.tsx
ui/src/services/submission.service.ts
ui/src/views/submissions/editable-submissions/FileSubmissionCreator.tsx
ui/src/views/submissions/submission-forms/form-components/ImportDataSelect.tsx
ui/src/views/submissions/submission-forms/forms/MultiSubmissionEditForm.tsx

Allows the user to press on a new "import directory" button on the file submissions page and choose a directory to import from. The directory will be inspected and an appropriate importer chosen automatically. The
submissions will then be imported in logical order, potentially including thumbnails, titles, descriptions etc.
Currently the following importers are implemented, because they are the ones I need:
* A flat file importer. Just gobbles up all the files in a directory.
* An importer for ActivityPub exports, like they fall out of Mastodon for example. Grabs all media posts that aren't direct messages and turns them into submissions with descriptions and tags.
* An importer for [this FurAffinity archiver](https://github.com/askmeaboutlo0m/faescape), which will import submissions with …

Multiple Submission Import

---

ui/src/stores/scroll-submission.store.ts
ui/src/views/submissions/editable-submissions/EditableSubmissionListItem.tsx
ui/src/views/submissions/submission-forms/forms/SubmissionEditForm.tsx

After editing it, since when you have a lot of submissions to edit it's really annoying to have to scroll down and find your spot again.
Not sure if this is a legitimate way to handle this, but hacking this in improved usability for me a whole bunch.

Scroll back to edited submission

---

electron-app/src/server/websites/telegram/telegram.service.ts

Just a misplaced parenthesis causing it.

Fix Telegram not logging in with 2FA enabled

---

electron-app/src/server/websites/artconomy/artconomy.service.ts

This PR adds a problem message if there are not enough tags to post to Artconomy, rather than failing upon attempt to post.
1. Create a post
2. Add Artconomy as a target
3. Use insufficient tags, with or without the 'extend default' option. Verify problem message is displayed.
4. Use sufficient tags and verify the problem message is removed.
Screenshot of problem message:

fix: Better handling of insufficient tags for Artconomy.

---

electron-app/src/server/websites/discord/discord.account.interface.ts
electron-app/src/server/websites/discord/discord.service.ts
ui/src/websites/discord/DiscordLogin.tsx

Discord forum channels require a `thread_name` to be passed as a query parameter of the first post, with subsequent posts in the same thread using a `thread_id` parameter in the body. Annoyingly, they validate it both ways, so we can't just always send those parameters, the user has to tick a box in the account settings if the target is a forum channel instead of a regular message channel.
This also changes file posting to stick everything into a single post instead of splitting it up into a notification message and one message per file. Presumably Discord didn't use to support that, but it does now, using the `files[n]` instead of `file` to attach files and a `payload_json` parameter to attach nested data into a multipart form.

Allow posting to Discord forum channels

---

electron-app/src/server/websites/itaku/itaku.service.ts
ui/src/websites/itaku/Itaku.tsx

Apparently itaku wants the field absent if you don't want to post to the feed. Even supplying `add_to_feed: false` enables it.

itaku post to feed & visibility options

---

electron-app/src/server/websites/discord/discord.service.ts

Discord have increased the basic file size limit for all users as mentioned on the discord server; verified online.

Increase discord size limit to 25Mb

---

electron-app/src/server/file-manipulation/manipulators/image.manipulator.worker.ts

It's capped at some fixed value, which botches loading images of larger resolutions for no good reasons This disables the limit in the deferred image manipualtion worker. Presumably the same manipulation isn't necessary in the non-deferred variant, since those images are tiny.
Upstream issue: https://github.com/jimp-dev/jimp/issues/915

Disable Jimp JPEG decoder memory limit

---

electron-app/src/server/submission/submission-importer/importers/importer.ts

For some reason default importing these worked before, but have now started importing `undefined` instead, causing the importer to stop working. Switching the imports over to not be default imports makes them work again.

Fix imports in submission importer

---

electron-app/src/server/websites/weasyl/weasyl.service.ts

“undefined” is someone’s username. (Weasyl gets about 2k requests for this every day.)
Note: I’m not able to test this; not sure if it needs a fallback `this.accountInformation.set(data._id, { folders: [] });`.

weasyl: Avoid requesting folders for undefined user

---

electron-app/src/server/websites/bluesky/bluesky.service.ts
electron-app/src/server/websites/website.base.ts

Appending tags already puts two newlines at the end of the description, there's no need for another space. I think there was also an off-by-one in the length check here, allowing one less character than the limit, which is now rectified.
This applies to the generic website tag appender and also adds some special handling for Bluesky, which needs to do a special dance to do its character counting. This unifies the logic, getting rid of a pile of duplicate code in the Bluesky integration.

Don't prepend space to first appended tag

---

electron-app/src/server/websites/mastodon/mastodon.service.ts

- The max width and height are now calculated based on the maximum number of pixels provided by the instance and the aspect ratio of the file.
- max post length is now set by the max characters setting from the instance.
- Adds support for a max filesize and max post length from Pleroma and Akkoma instances.
- The chunk size is now determined by the max media attachments setting from Mastodon and Pleroma instances
- Updates the accepted filetypes based on what standard Mastodon supports. Ideally this would be from the list of mime types provided by the instance though.

Fix scaling and limits for Mastodon and Pleroma/Akkoma

---

commons/src/interfaces/websites/bluesky/bluesky.file.options.interface.ts
commons/src/interfaces/websites/bluesky/bluesky.notification.options.interface.ts
commons/src/interfaces/websites/mastodon/mastodon.file.options.interface.ts
commons/src/interfaces/websites/mastodon/mastodon.notification.options.interface.ts
commons/src/websites/bluesky/bluesky.file.options.ts
commons/src/websites/bluesky/bluesky.notification.options.ts
commons/src/websites/mastodon/mastodon.file.options.ts
commons/src/websites/mastodon/mastodon.notification.options.ts
electron-app/src/server/websites/bluesky/bluesky.service.ts
electron-app/src/server/websites/mastodon/mastodon.service.ts
ui/src/websites/bluesky/Bluesky.tsx
ui/src/websites/mastodon/Mastodon.tsx

Allows specifying a reply to post URL for those two services, because I wanna be able to post threads. This interface isn't too comfortable, since it requires manual copying of the parent post URL. But letting your wire up a parent post from within PostyBirb is left as an exercise for someone else or future me, this is currently already useful as a minimum viable product.

Replies for Mastodon and Bluesky

---

electron-app/src/server/websites/bluesky/bluesky.service.ts

Properly validate Bluesky description length, it wasn't using the plain text version of the description, so its character count was inflated by counting the raw HTML. This is rectified now, by using the same kind of code that other services use.
The error message also now says "characters" again instead of "graphemes", since graphemes are what humans interpret as characters, even if the computer may see them as a collection of characters.
Require alt text for Bluesky again, with an explanation that that's a bug on their side in the hopes that it will stop people reporting it to PostyBirb's side.
cc @aneillans

Fix Bluesky description length and alt text validation

---

electron-app/src/server/websites/itaku/itaku.service.ts

As mentioned on Discord, it appears Itaku has a 5000 character limit on descriptions; added this to the validation as a problem

Itaku: Add a 5000 char description limit on validation

---

electron-app/src/server/websites/bluesky/bluesky.service.ts

After posting show the friendly URL on Posting in Log
Resolves #242

BlueSky - Show Friendly Url on Post

---

electron-app/src/server/websites/artconomy/artconomy.service.ts
package.json

This PR adds a check for descriptions which exceed the 2000 character limit imposed by Artconomy, providing an error when present.
1. Log into an Artconomy account
2. Create a file submission
3. Enter a default description with a length over 2000 characters
4. Verify error message shown upon save
5. Replace default description with one that is shorter than 2000 characters
6. Add a description override for Artconomy with a length greater than 2000 characters
7. Verify error message shown upon save

fix: Description Length Limit

---

commons/package-lock.json
commons/package.json
commons/src/index.ts
commons/src/interfaces/websites/megalodon/megalodon.account.interface.ts
commons/src/interfaces/websites/pixelfed/pixelfed.account.interface.ts
commons/src/interfaces/websites/pleroma/pleroma.account.interface.ts
commons/src/interfaces/websites/pleroma/pleroma.file.options.interface.ts
commons/src/interfaces/websites/pleroma/pleroma.notification.options.interface.ts
commons/src/websites/pleroma/pleroma.file.options.ts
commons/src/websites/pleroma/pleroma.notification.options.ts
commons/src/websites/pleroma/pleroma.options.ts
commons/src/websites/websites.ts
electron-app/package-lock.json
electron-app/package.json
electron-app/src/server/websites/mastodon/mastodon.service.ts
electron-app/src/server/websites/megalodon/megalodon.service.ts
electron-app/src/server/websites/pixelfed/pixelfed.service.ts
electron-app/src/server/websites/pleroma/pleroma.controller.ts
electron-app/src/server/websites/pleroma/pleroma.module.ts
electron-app/src/server/websites/pleroma/pleroma.service.ts
electron-app/src/server/websites/website-provider.service.ts
electron-app/src/server/websites/websites.module.ts
package-lock.json
ui/package-lock.json
ui/package.json
ui/src/websites/mastodon/MastodonLogin.tsx
ui/src/websites/pixelfed/PixelfedLogin.tsx
ui/src/websites/pleroma/Pleroma.tsx
ui/src/websites/pleroma/PleromaLogin.tsx
ui/src/websites/website-registry.ts

Lot of refactoring to move Pixelfed, Mastodon and Pleroma onto a common code structure entirely, removing a LOT of duplication.
This is forked from my Pleroma branch, and *should* fully support Pleroma with no issues now - as does NOT use the Mastodon compatibility API at all. I've tested this with my own Pleroma test instance and didn't get any issues. 
Bump Megalodon to v7; will move to v8 once I have moved misskey off to it's own lib.

Megalodon refactor

---

electron-app/src/server/websites/bluesky/bluesky.service.ts
electron-app/src/server/websites/megalodon/megalodon.service.ts
electron-app/src/server/websites/misskey/misskey.service.ts
electron-app/src/server/websites/website.base.ts

On Bluesky, Mastodon and Misskey, rather than just silently truncating tags to some unexpected subset.

Warn about tags that don't fit into description

---

commons/src/interfaces/submission/file-record.interface.ts
commons/src/interfaces/submission/submission-update.interface.ts
electron-app/src/server/submission/file-submission/file-submission.service.ts
electron-app/src/server/submission/parser/parser.service.ts
electron-app/src/server/submission/post/interfaces/file-post-data.interface.ts
electron-app/src/server/submission/submission.service.ts
electron-app/src/server/websites/bluesky/bluesky.service.ts
electron-app/src/server/websites/megalodon/megalodon.service.ts
electron-app/src/server/websites/misskey/misskey.service.ts
ui/src/views/submissions/submission-forms/forms/SubmissionEditForm.tsx
ui/src/websites/bluesky/Bluesky.tsx
ui/src/websites/mastodon/Mastodon.tsx
ui/src/websites/misskey/MissKey.tsx
ui/src/websites/pixelfed/Pixelfed.tsx

Rather than having a single alt text field in individual website forms that then get copied for every uploaded file and then causes a screen reader to rattle off the same description multiple times. Alt text fields in the individual forms are still present for compatibility, but they will only be used as fallback if no file-specific values are provided.
Ping @aneillans because if I recall correctly you had something like this in mind too.

Allow specifying alt texts in submission files

---

ui/src/websites/bluesky/Bluesky.tsx

The Bluesky UI form currently incorrectly still says Alt Text instead of Fallback Alt Text; this PR just updates that.

Correct bluesky alt text UI

---

commons/src/interfaces/websites/bluesky/bluesky.file.options.interface.ts
commons/src/interfaces/websites/bluesky/bluesky.notification.options.interface.ts
electron-app/src/server/websites/bluesky/bluesky.service.ts
ui/src/websites/bluesky/Bluesky.tsx

It ended up being treated as a nonexistent option in the UI and as "nobody" in the posting code. Now it gets treated the same as an empty string, which is "everybody", as it ought to. Thanks ArgonVile for pointing this out.

Handle undefined Bluesky threadgate value properly

---

electron-app/src/server/websites/bluesky/bluesky.service.ts
electron-app/src/server/websites/megalodon/megalodon.service.ts

Add's a warning to validation if no {tags} shortcut is found in a file posting for these networks, given that is how they currently handle most of their discoverability (and it's currently catching people out)

Add no tags warning (BlueSky and Megalodon)

---

ui/src/views/submissions/scheduled-submissions/ScheduledSubmissions.tsx

Add's a confirmation prompt when a user clicks unschedule all to try and counter accidental clicks

Confirmation on unschedule

---

electron-app/src/server/websites/hentai-foundry/hentai-foundry.service.ts

As mentioned on Discord, this brings in a 1500 x 1500 scaling capability for images uploaded on Hentai Foundry in addition to the file size restriction when auto scaling is enabled to ensure that things don't keep falling into manual moderation.
After discussion, and checking with the max limits allowed, reduced the file size too.

Hentai Foundry: Scaling updates

---

electron-app/src/server/websites/twitter/twitter.service.ts

Adds the # to the twitter tags when {tags} is used
Adds warnings to the {tags} missing etc

Add warnings for tag insertion, correct hash missing on tag insertion

---

electron-app/src/server/utils/browser-window.util.spec.ts
electron-app/src/server/utils/browser-window.util.ts
electron-app/src/server/websites/furry-network/furry-network.service.ts
electron-app/src/server/websites/ko-fi/ko-fi.service.ts
electron-app/src/server/websites/newgrounds/newgrounds.service.ts
electron-app/src/server/websites/patreon/patreon.service.ts
electron-app/src/server/websites/subscribe-star-adult/subscribe-star-adult.service.ts
electron-app/src/server/websites/subscribe-star/subscribe-star.service.ts
electron-app/src/server/websites/telegram/telegram.service.ts

For some reason Ko-Fi post.body can be \u0000\u0007\u0000{"success":true}\u0003
Report: https://discord.com/channels/395931304870281216/580751000835588156/1216467099975942334
Fixes BrowserWindowUtil.runScriptOnPage error handling to be more informative instead of just `Script failed to execute`
Report: https://discord.com/channels/395931304870281216/580751000835588156/1217943590718799962

Fix Ko-Fi post status parsing, Furry-Network error inspection

---

electron-app/src/server/websites/artconomy/artconomy.service.ts

Artconomy has updated its maximum size limit from 100MB down to 50MB. This PR changes the code to reflect this. Note that the supported size is internally marked as slightly smaller to account for overhead, since the limit is at the request size level.
1. Attempt to upload a file that's too large.
2. Verify it is either auto-resized or fails if the file cannot be resized by PostyBirb.

fix: Update Artconomy post limit

---

electron-app/src/server/websites/telegram/telegram-description.parser.ts
electron-app/src/server/websites/telegram/telegram-description.spec.ts
electron-app/src/server/websites/telegram/telegram.service.ts

Increased channel limit up to 400 (previosly was 200)
Telegram now properly parses links in the description

Increase telegram channel limit (from 200 to 400) and fix link parsing

---

electron-app/src/server/websites/twitter/twitter-api.service.ts

This pull request removes the escape mechanism from Twitter posts when tagging usernames. This feature was initially added to reduce the likelihood of PostyBirb's API keys getting banned. However, now that each individual user generates their own API keys, each individual is responsible for their own use of the API and one getting banned does not affect other users.
1. Create a new post on Twitter which mentions another user.
2. Verify the person is properly mentioned as expected.

fix: Stop escaping Twitter usernames.

---

electron-app/src/server/websites/picarto/picarto.service.ts

As discussed on Discord, non-members on Picarto are capped at 4k size.

Resize Picarto to max 4k

---

electron-app/src/server/websites/itaku/itaku.service.ts
ui/src/websites/itaku/Itaku.tsx

By uploading them as separate images and then creating a post that references them. This is how multi-image posting works on Itaku, it's really strange.
If something goes wrong with posting the images, the user will end up with duplicates. Not much we can really do about it though and that's always a risk with retrying a post anyway, since the user might get a failed response even though the image posted fine.
This requires "share on feed" to be turned on, since posts are always shared on the feed.

Allow posting multiple files to Itaku

---

README.md
commons/src/interfaces/settings/settings.interface.ts
electron-app/package.json
electron-app/src/app/settings.ts
electron-app/src/global.d.ts
electron-app/src/main.ts
ui/src/stores/settings.store.ts
ui/src/views/settings/SettingsView.tsx

Feature request: https://discord.com/channels/395931304870281216/395933121981317120/1280074401701691453
Also slightly reworked global.d.ts to properly add types to global

New setting: Close on quit

---

electron-app/src/server/websites/deviant-art/deviant-art.service.ts

Report: https://discord.com/channels/395931304870281216/580751000835588156/1288792123096825866

DeviantArt: add warning about invalid title

---

commons/src/interfaces/settings/settings.interface.ts
electron-app/src/app/settings.ts
electron-app/src/server/file-manipulation/file-manipulation.service.ts
electron-app/src/server/submission/parser/parser.service.ts
electron-app/src/server/websites/bluesky/bluesky.service.ts
electron-app/src/server/websites/interfaces/scaling-options.interface.ts
ui/src/stores/settings.store.ts
ui/src/views/settings/SettingsView.tsx

A few things in here, check the individual commits for more details. The main issue here is that when you post to Bsky, the image gets scaled to a dinky 1000x1000 size, which is a) wrong, because it exceeds the maximum scale amount I set and b) bad, because it could just use a pretty good quality JPEG instead and not lose any size.
So this PR does a few things in that regard.
It takes the maximum scale amount set by the user relative to the *original* image size, not the size after rescaling the image according to website limits. Presumably this was the intended behavior to begin with, so this is just a bugfix.
Maybe somewhat controversially, it now prefers quality reduction over size reduction by default, at least for images that don't have an alpha channel. Reducing JPEG quality is …

Fix and improve autoscaling behavior

---

electron-app/src/server/websites/bluesky/bluesky.service.ts
ui/src/websites/bluesky/Bluesky.tsx

Sending '' as alt text is valid and the official solution (https://github.com/bluesky-social/social-app/blob/fa2072cefa0379fd1ea36ad109b8d24721838958/jest/test-pds.ts#L251)
I tested it on my end and it'll send images just fine without alt texts.

fix: allow Bluesky Posts without alt text

---

electron-app/src/server/http/http.util.ts
electron-app/src/server/submission/submission.service.ts
electron-app/src/server/submission/validator/validator.service.ts
electron-app/src/server/websites/e621/e621.service.ts
electron-app/src/server/websites/megalodon/megalodon.service.ts
electron-app/src/server/websites/website.base.ts

https://github.com/leaftail1880/postybirb-plus/releases/tag/v3.1.54

E621 tag warning bounty

---

electron-app/src/server/websites/aryion/aryion.service.ts
ui/src/websites/aryion/Aryion.tsx

At some point Aryion added support for a few different file types. This pull request allows Postybirb to submit PDFs. It also allows Postybirb to disregard warnings from submissions. More details about that in the code, since it may or may not be the approach that you'd like to take. >w<
Aryion supports other file types that I have not added support for: docx, rtf, etc.. Adding support for them would likely be straightforward (just adding them to the supported files lists), but I haven't had time to test to make sure that they're all working.

Aryion PDF support

---

ui/src/websites/pillowfort/Pillowfort.tsx

Adds the ability for posts to pillowfort to be marked for only visible to logged in users (looked to be the only option missing)

Add option for PillowFort - only logged in users

---

electron-app/src/server/websites/discord/discord.service.ts

For Discord accounts created in version <= 3.1.60, the server boost level is null when version 3.1.61 attempts to read it to determine the appropriate file size.
This PR improves backwards compatibility with checking the boost level. If null, or some other unexpected value, it will be reset to boost level 0 (the default).
Also fixes an erroneous `$` character in a warning message.

Fix for Discord Backwards Compatibility and Typo
