mvdicarlo/postybirb-plus

electron-app/main.js, electron-app/package.json, electron-app/src/file-manipulation/pools/image-manipulation-pool.service.ts, electron-app/src/submission/interfaces/submission-package.interface.ts, electron-app/src/submission/submission.service.ts, electron-app/src/submission/validator/interfaces/problems.interface.ts, electron-app/src/utils/browser-window.util.ts, electron-app/src/websites/deviant-art/deviant-art.defaults.ts, electron-app/src/websites/deviant-art/deviant-art.interface.ts, electron-app/src/websites/deviant-art/deviant-art.service.ts, electron-app/src/websites/hentai-foundry/hentai-foundry.service.ts, electron-app/src/websites/mastodon/mastodon.defaults.ts, electron-app/src/websites/mastodon/mastodon.interface.ts, electron-app/src/websites/mastodon/mastodon.service.ts, electron-app/src/websites/new-tumbl/new-tumbl.service.ts, package.json, ui/package.json, ui/src/views/submissions/submission-forms/forms/SubmissionEditForm.tsx, ui/src/views/submissions/submission-image-cropper/SubmissionImageCropper.tsx, ui/src/websites/deviant-art/DeviantArt.tsx, ui/src/websites/fur-affinity/FurAffinity.tsx, ui/src/websites/furry-network/FurryNetwork.tsx, ui/src/websites/hentai-foundry/HentaiFoundry.tsx, ui/src/websites/inkbunny/InkbunnyLogin.tsx, ui/src/websites/mastodon/Mastodon.tsx, ui/src/websites/mastodon/MastodonLogin.tsx, ui/src/websites/twitter/Twitter.tsx
Fixes and tweaks based on user testing and feedback.
=> Merge v3.0.7

electron-app/package.json, electron-app/src/description-parsing/html/html.parser.ts, electron-app/src/websites/e621/e621.service.ts, package.json, ui/package.json, ui/src/styles/submission.css, ui/src/views/submissions/editable-submissions/EditableSubmissionListItem.tsx, ui/src/views/submissions/editable-submissions/EditableSubmissions.tsx, ui/src/views/submissions/submission-forms/form-components/DescriptionInput.tsx, ui/src/views/submissions/submission-forms/form-components/TagInput.tsx, ui/src/views/submissions/submission-forms/forms/SubmissionEditForm.tsx, ui/src/websites/derpibooru/Derpibooru.tsx, ui/src/websites/e621/e621.tsx, ui/src/websites/e621/e621Login.tsx
Tweaks, bug fixes, UI changes.
=> Merge v3.0.9

electron-app/package.json, electron-app/src/file-manipulation/file-manipulation.service.ts, electron-app/src/websites/newgrounds/newgrounds.service.ts, package.json, ui/package.json, ui/src/styles/submission.css, ui/src/views/submissions/submission-forms/forms/MultiSubmissionEditForm.tsx, ui/src/views/submissions/submission-forms/forms/SubmissionEditForm.tsx, ui/src/views/submissions/submission-forms/forms/SubmissionTemplateEditForm.tsx
Minor tweaks and Newgrounds fix.
=> Merge v3.0.10

electron-app/package.json, electron-app/src/server/utils/browser-window.util.ts, electron-app/src/server/websites/deviant-art/deviant-art.service.ts, electron-app/src/server/websites/furry-life/furry-life.service.ts, electron-app/src/server/websites/furry-network/furry-network.service.ts, electron-app/src/server/websites/inkbunny/inkbunny.service.ts, electron-app/src/server/websites/patreon/patreon.service.ts, electron-app/src/server/websites/pillowfort/pillowfort.service.ts, electron-app/src/server/websites/tumblr/tumblr.service.ts, package.json, ui/package.json, ui/src/views/submissions/submission-forms/forms/MultiSubmissionEditForm.tsx, ui/src/views/submissions/submission-forms/forms/SubmissionEditForm.tsx, ui/src/views/submissions/submission-forms/forms/SubmissionTemplateEditForm.tsx, ui/src/websites/furry-network/FurryNetworkLoginHelp.tsx
=> Merge v3.0.17

electron-app/src/server/websites/artconomy/artconomy.service.ts, ui/src/websites/artconomy/Artconomy.tsx
This pull request adds journal support to Artconomy.com submissions.
**Screenshots**: Always include screenshots if there is any change to the UI.
1. Log into an Artconomy.com account
2. Create a new notification submission and post it.
**Reviewers**
=> Add journal support for Artconomy.

electron-app/src/server/websites/artconomy/artconomy.service.ts
This PR removes the use of Authorization tokens as a method of authenticating requests to Artconomy.com. It also grabs the CSRF token from the headers of the login check instead of an explicit value returned from the requester info endpoint.
1. Log in to your Artconomy account.
2. Attempt to post a file with no thumbnail
3. Attempt to post a file with a thumbnail
4. Attempt to post a journal.
**Reviewers**
=> Remove use of AuthTokens, get CSRF token from headers

electron-app/package.json, electron-app/src/server/websites/deviant-art/deviant-art.service.ts, package.json, ui/package.json
DeviantArt: Fix bad api now that category is no longer a thing
=> Start v3.0.45

commons/src/index.ts, commons/src/interfaces/websites/manebooru/manebooru.file.options.interface.ts, commons/src/websites/manebooru/manebooru.file.options.ts, commons/src/websites/manebooru/manebooru.options.ts, commons/src/websites/websites.ts, electron-app/src/server/websites/manebooru/manebooru.module.ts, electron-app/src/server/websites/manebooru/manebooru.service.ts, electron-app/src/server/websites/website-provider.service.ts, electron-app/src/server/websites/websites.module.ts, ui/src/websites/manebooru/Manebooru.tsx, ui/src/websites/website-registry.ts
This Pull Request adds support for the Manebooru ([manebooru.art](https://manebooru.art)) Site.
I've run it through a basic test to ensure that account management works as well as posting art has no issues. Manebooru uses the same backend as Derpibooru so most of the code is copied from there with changes to make it work against Manebooru.
=> Add Manebooru Support

electron-app/src/server/websites/mastodon/mastodon.service.ts
=> Show urls for Mastodon

commons/src/interfaces/submission/file-record.interface.ts, electron-app/package.json, electron-app/src/server/file-manipulation/file-manipulation.service.ts, electron-app/src/server/submission/file-submission/file-submission.service.ts, electron-app/src/server/submission/parser/parser.service.ts, electron-app/src/server/websites/interfaces/scaling-options.interface.ts, electron-app/src/server/websites/mastodon/mastodon.module.ts, electron-app/src/server/websites/mastodon/mastodon.service.ts, package.json, ui/package.json
Flatted into a single commit; ended up mangling my last PR as merged and closed into a develop branch accidentally!
=> Mastodon improved large image handling

commons/src/index.ts, commons/src/interfaces/websites/pixelfed/pixelfed.account.interface.ts, commons/src/interfaces/websites/pixelfed/pixelfed.file.options.interface.ts, commons/src/websites/pixelfed/pixelfed.file.options.ts, commons/src/websites/pixelfed/pixelfed.options.ts, commons/src/websites/websites.ts, electron-app/src/server/websites/pixelfed/pixelfed.module.ts, electron-app/src/server/websites/pixelfed/pixelfed.service.ts, electron-app/src/server/websites/website-provider.service.ts, electron-app/src/server/websites/websites.module.ts, ui/src/websites/pixelfed/Pixelfed.tsx, ui/src/websites/pixelfed/PixelfedLogin.tsx, ui/src/websites/website-registry.ts
=> PixelFed support

electron-app/src/server/websites/telegram/telegram.service.ts
Now it shows only channels/chats where user can send media
=> Fix: Telegram.loadChannels

electron-app/src/server/websites/aryion/aryion.service.ts
A very small change, but thought I'd hop in and do it. Posting to Aryion has been broken for ages now.
=> Just changes the parser to BBCode for Aryion.

electron-app/package.json, electron-app/src/server/submission/submission-importer/importers/fa-archive-importer.ts, package.json, ui/package.json
Fixing the thumbnail check to allow for .gif files for the FA Archive importer.
=> Fix thumbnail check

electron-app/src/server/websites/deviant-art/deviant-art.service.ts, ui/src/websites/deviant-art/DeviantArt.tsx
Closes old #70 and also add tag limit to 30
=> DeviantArt fixes

electron-app/src/server/notification/notification.service.spec.ts
Before that pr notification service test will fail. Note that e2e still fails, ill fix that after contributing roadmap will be done.
=> electron-app test fix

electron-app/src/server/websites/itaku/itaku.service.ts
I could have sworn I tested this extensively but I guess this snuck around me somehow.
=> Fix Itaku posting

commons/src/interfaces/websites/bluesky/bluesky.file.options.interface.ts, commons/src/interfaces/websites/bluesky/bluesky.notification.options.interface.ts, commons/src/websites/bluesky/bluesky.file.options.ts, commons/src/websites/bluesky/bluesky.notification.options.ts, electron-app/package-lock.json, electron-app/package.json, electron-app/src/server/websites/bluesky/bluesky.service.ts, package-lock.json, ui/package-lock.json, ui/package.json, ui/src/websites/bluesky/Bluesky.tsx
- Adds tag input as per Mastodon etc (allows things to be used with furryli.st, custom feeds, improved discovery easily etc)
- Adds multiple image support
- Adds Label support that Bluesky have recently exposed
=> Bluesky updates

electron-app/src/server/websites/bluesky/bluesky.service.ts, ui/src/websites/bluesky/BlueskyLogin.tsx
- Adds support for BlueSky RichText (mostly links)
- Hopefully fixes the problems around length handling (now correctly uses graphemes)
- Updates the hint text for usernames to try and make it clearer what to login with
- Change Alt Text missing to be a warning, not mandatory value
=> Bluesky improvements

commons/src/index.ts, commons/src/interfaces/websites/furtastic/furtastic.account.interface.ts, commons/src/interfaces/websites/furtastic/furtastic.file.options.interface.ts, commons/src/websites/furtastic/furtastic.file.options.ts, commons/src/websites/furtastic/furtastic.options.ts, commons/src/websites/websites.ts, electron-app/src/server/websites/furtastic/furtastic.module.ts, electron-app/src/server/websites/furtastic/furtastic.service.ts, ui/src/websites/furtastic/Furtastic.tsx, ui/src/websites/furtastic/FurtasticLogin.tsx, ui/src/websites/furtastic/Providers.tsx, ui/src/websites/website-registry.ts
This PR is to enable image upload support on the Furtastic platform, for accounts that have an API key enabled.
I have recreated the PR as it was extremely messy with a ton of confusing commits by me. :(
=> Furtastic: Image upload support on PostyBirb

electron-app/src/server/websites/website-provider.service.ts, electron-app/src/server/websites/websites.module.ts, ui/src/websites/furtastic/Furtastic.tsx
=> Furtastic: Fixed broken imports.

electron-app/src/server/websites/mastodon/mastodon.service.ts, electron-app/src/server/websites/misskey/misskey.service.ts, electron-app/src/server/websites/website.base.ts
better support for source on this cites, less duplicated code and error fix for misskey
=> fix: mastodon and misskey

commons/package-lock.json, commons/package.json, electron-app/package-lock.json, electron-app/package.json, electron-app/src/server/websites/furtastic/furtastic.service.ts, package-lock.json, ui/package-lock.json, ui/package.json, ui/src/websites/furtastic/FurtasticLogin.tsx
Tweaks for Furtastic as mentioned by Loxie on Discord:
- Improve the login message to mention email address
- Added PDF to allowed file types
Also bumped megalodon a minor version while I was in there.
=> Updates to accepted files for Furtastic, improved login message

commons/package-lock.json, commons/package.json, commons/src/index.ts, commons/src/interfaces/websites/pleroma/pleroma.account.interface.ts, commons/src/interfaces/websites/pleroma/pleroma.file.options.interface.ts, commons/src/interfaces/websites/pleroma/pleroma.notification.options.interface.ts, commons/src/websites/pleroma/pleroma.file.options.ts, commons/src/websites/pleroma/pleroma.notification.options.ts, commons/src/websites/pleroma/pleroma.options.ts, commons/src/websites/websites.ts, electron-app/package-lock.json, electron-app/package.json, electron-app/src/server/websites/pleroma/pleroma.controller.ts, electron-app/src/server/websites/pleroma/pleroma.module.ts, electron-app/src/server/websites/pleroma/pleroma.service.ts, electron-app/src/server/websites/website-provider.service.ts, electron-app/src/server/websites/websites.module.ts, ui/package-lock.json, ui/package.json, ui/src/websites/pleroma/Pleroma.tsx, ui/src/websites/pleroma/PleromaLogin.tsx, ui/src/websites/website-registry.ts
Once this is merged down, I want to do a pass to merge and cleanup all megalodon consuming services. 
There's a lot of duplicated code that can now be removed and cleaned up.
=> Pleroma Support

electron-app/src/server/websites/discord/discord.service.ts, ui/src/websites/bluesky/BlueskyLogin.tsx
As mentioned in pb's discord server bugs channel: https://discord.com/channels/395931304870281216/395932178682478592/1171526784634855484
=> Fix discord link and add bluesky login warnings

electron-app/src/main.ts
Previously, there was no way to change base folder and port using cli. Now its possible
=> Fix cli options

electron-app/src/server/websites/megalodon/megalodon.service.ts, electron-app/src/server/websites/pleroma/pleroma.service.ts
Resolve regressions identified in #282 
However, it should be noted that the specific compatibility is for Pleroma, Akkoma is not guaranteed nor specifically mentioned (Akkoma is a hard fork of Pleroma, so there is no way to specifically guarantee compatibility)
=> Resolve Pleroma Regressions

commons/src/interfaces/websites/bluesky/bluesky.file.options.interface.ts, commons/src/interfaces/websites/bluesky/bluesky.notification.options.interface.ts, commons/src/websites/bluesky/bluesky.file.options.ts, commons/src/websites/bluesky/bluesky.notification.options.ts, electron-app/package-lock.json, electron-app/package.json, electron-app/src/server/websites/bluesky/bluesky.service.ts, package-lock.json, ui/package-lock.json, ui/package.json, ui/src/websites/bluesky/Bluesky.tsx
Adds the ability to limit who can reply to your BlueSky posts as per the recent update
=> Bluesky reply options

electron-app/src/server/websites/bluesky/bluesky.service.ts
Report: https://discord.com/channels/395931304870281216/395932207925166091/1219561286946525224
=> feat: added bluesky rating warning

electron-app/src/server/websites/megalodon/megalodon.service.ts
This can happen if the server is still processing the media on some instances, so now we retry it a few times with an increasing backoff delay.
See https://meow.social/@TransparencyReports/112581905483800997
=> Retry Mastodon posts when receiving a 422 error

ui/src/websites/e621/e621.tsx
E621 has 3 ratings, Safe, Questionable, and Explicit. This PR allows users to select from those rather than the 4 default ones.
=> Add e621 ratings

commons/src/interfaces/websites/custom/custom.account.interface.ts, electron-app/src/server/websites/custom/custom.service.ts, ui/src/websites/custom/CustomAccountInfo.tsx
Transmits an array of them, one element per file. Default field is called "alt".
=> Support alt text for custom website

electron-app/src/server/websites/telegram/telegram.service.ts
Report: https://discord.com/channels/395931304870281216/580751000835588156/1288905336014770196
=> Telegram: support groups

electron-app/src/server/submission/parser/parser.service.ts, electron-app/src/server/submission/post/interfaces/file-post-data.interface.ts, electron-app/src/server/websites/bluesky/bluesky.service.ts
=> fix: add aspect ratio to bsky embed

electron-app/src/server/websites/ko-fi/ko-fi.service.ts
According to Hazel in Discord, 700 appears to be the limit. Anything beyond that value just gets cut off.
=> Define a character limit for Ko-Fi

electron-app/src/server/websites/e621/e621.service.ts, ui/src/websites/e621/e621.tsx
https://discord.com/channels/395931304870281216/1151843195534200984/1316358215885258772
=> E621 sources limit increase

README.md
This PR fixes some minor typos in the main README.md
=> fix: minor readme typos

electron-app/src/server/websites/telegram/telegram.service.ts
https://discord.com/channels/395931304870281216/395932207925166091/1339360057065865248
=> fix: telegram channels loading

electron-app/src/server/websites/twitter/models/api-response.model.ts, electron-app/src/server/websites/twitter/twitter-api.service.ts
=> fix: more detailed twitter errors

electron-app/src/server/websites/fur-affinity/fur-affinity.service.ts, ui/src/websites/fur-affinity/FurAffinity.tsx
https://discord.com/channels/395931304870281216/395932207925166091/1360318581300269188
=> feat: increase tag limit to 500

electron-app/src/server/submission/post/cancellation/cancellation-token-dynamic.ts, electron-app/src/server/submission/post/cancellation/cancellation-token.ts, electron-app/src/server/utils/rate-limiter.util.spec.ts, electron-app/src/server/utils/rate-limiter.util.ts, electron-app/src/server/websites/e621/e621.service.ts
https://discord.com/channels/395931304870281216/1329446763995594825/1360288624654028892
=> fix: add rate limit handling for e621

electron-app/src/server/websites/fur-affinity/fur-affinity.service.ts
most of the error reporst from fa are "cannot read property includes of undefined", this fixes them by making errors more detailed
=> fix: more detailed errors on fa
